# Generated by Django 5.0.8 on 2025-12-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discipline', models.CharField(choices=[('football', 'Piłka nożna'), ('volleyball', 'Siatkówka'), ('basketball', 'Koszykówka'), ('tennis', 'Tenis'), ('wrestling', 'Zapasy')], max_length=50)),
                ('is_private', models.BooleanField(default=True)),
                ('access_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
