# Generated by Django 5.0.8 on 2025-12-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
