# Generated by Django 5.0.8 on 2025-12-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_private',
        ),
    ]
