# Generated by Django 5.0.8 on 2025-12-28 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_tournament_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='entry_mode',
            field=models.CharField(choices=[('ORGANIZER_ONLY', 'Tylko organizator'), ('OPEN_APPROVAL', 'Zgłoszenia z zatwierdzaniem'), ('ACCOUNT_BASED', 'Uczestnicy z kontami')], default='ORGANIZER_ONLY', max_length=32),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PLACEHOLDER', 'Placeholder'), ('PENDING', 'Oczekuje na zatwierdzenie'), ('APPROVED', 'Zatwierdzona')], default='PLACEHOLDER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
        ),
    ]
