# Generated by Django 5.0.8 on 2025-12-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_entry_mode_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='competition_type',
            field=models.CharField(choices=[('TEAM', 'Drużynowy'), ('INDIVIDUAL', 'Indywidualny')], default='TEAM', max_length=16),
        ),
    ]
