# Generated by Django 5.0.8 on 2025-12-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_competition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_format',
            field=models.CharField(choices=[('CUP', 'Puchar'), ('LEAGUE', 'Liga'), ('MIXED', 'Mieszany')], default='LEAGUE', max_length=16),
        ),
    ]
