# Generated by Django 5.0.8 on 2025-12-29 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_participants_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='tournaments.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='tournaments.division'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_tournament_division_name'),
        ),
    ]
