# Generated by Django 5.0.8 on 2025-12-29 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_group_tournament_status_alter_team_status_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='status',
        ),
    ]
