# Generated by Django 5.0.8 on 2025-12-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_remove_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
