# Generated by Django 5.0.8 on 2025-12-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournament_archived_at_tournament_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='archived_at',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Logiczne archiwum – turniej ukryty na głównych listach'),
        ),
    ]
