# Generated by Django 5.0.8 on 2026-01-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_remove_tournament_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, help_text='Ogólna lokalizacja turnieju (opcjonalna)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, help_text='Data zakończenia turnieju (opcjonalna)', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, help_text='Data rozpoczęcia turnieju (opcjonalna)', null=True),
        ),
    ]
