# Generated by Django 5.0.8 on 2026-01-01 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_location_alter_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['round_number', 'id']},
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, help_text='Lokalizacja meczu (opcjonalna)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Data rozegrania meczu (opcjonalna)', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Godzina rozpoczęcia meczu (opcjonalna)', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Grupa (tylko dla fazy grupowej)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.group'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Numer kolejki / rundy', null=True),
        ),
    ]
