# Generated by Django 5.0.8 on 2026-01-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_match_options_match_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Zwycięzca meczu (wymagany w KO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Otwarty'), ('CLOSED', 'Zamknięty')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
