# Generated by Django 5.0.8 on 2026-01-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_match_winner_stage_status_alter_match_away_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Zaplanowany'), ('IN_PROGRESS', 'W trakcie'), ('FINISHED', 'Zakończony')], default='SCHEDULED', max_length=20),
        ),
    ]
