# Generated by Django 5.0.8 on 2026-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_match_result_entered_alter_match_away_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('LEAGUE', 'Liga'), ('GROUP', 'Faza grupowa'), ('KNOCKOUT', 'Puchar (KO)'), ('THIRD_PLACE', 'Mecz o 3. miejsce')], max_length=20),
        ),
    ]
