# Generated by Django 5.0.8 on 2026-01-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_alter_stage_stage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='participants_count',
        ),
    ]
