# Generated by Django 5.0.8 on 2026-01-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_remove_tournament_participants_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_penalty_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='decided_by_penalties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalty_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
