# Generated by Django 5.0.8 on 2026-01-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_match_away_penalty_score_match_decided_by_penalties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_extra_time_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_extra_time_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='went_to_extra_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='discipline',
            field=models.CharField(choices=[('football', 'Piłka nożna'), ('volleyball', 'Siatkówka'), ('basketball', 'Koszykówka'), ('handball', 'Piłka ręczna'), ('tennis', 'Tenis'), ('wrestling', 'Zapasy')], max_length=50),
        ),
    ]
