# Generated by Django 5.0.8 on 2026-01-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_match_away_extra_time_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tennis_sets',
            field=models.JSONField(blank=True, default=None, help_text='Dla tenisa: lista setów w gemach (opcjonalnie z tie-breakiem).', null=True),
        ),
    ]
