# Generated by Django 5.0.8 on 2026-01-14 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_tournament_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_code',
            field=models.CharField(blank=True, help_text='Kod do samodzielnej rejestracji (ACCOUNT_BASED).', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='entry_mode',
            field=models.CharField(choices=[('ORGANIZER_ONLY', 'Tylko organizator'), ('OPEN_APPROVAL', 'Zgłoszenia z zatwierdzaniem'), ('ACCOUNT_BASED', 'Uczestnicy z kontami')], default='OPEN_APPROVAL', max_length=32),
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='uniq_registration_tournament_user'),
        ),
    ]
