# Generated by Django 5.0.8 on 2026-01-15 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_tournament_registration_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='registered_user',
            field=models.ForeignKey(blank=True, help_text='Użytkownik, który zajął ten slot w trybie SELF_REGISTER.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='entry_mode',
            field=models.CharField(choices=[('MANAGER', 'Organizator + asystent'), ('ORGANIZER_ONLY', 'Tylko organizator'), ('SELF_REGISTER', 'Samodzielna rejestracja')], default='MANAGER', max_length=32),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_code',
            field=models.CharField(blank=True, help_text='Kod do samodzielnej rejestracji (tryb SELF_REGISTER).', max_length=32, null=True),
        ),
    ]
