# Generated by Django 5.0.8 on 2026-01-16 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_team_registered_user_alter_tournament_entry_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='join_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Czy użytkownicy mogą dołączać do turnieju przez konto + kod (join link + code).'),
        ),
        migrations.AddField(
            model_name='tournamentmembership',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Granularne uprawnienia asystenta w danym turnieju (JSON).'),
        ),
        migrations.AlterField(
            model_name='team',
            name='registered_user',
            field=models.ForeignKey(blank=True, help_text='(Opcionalne) Użytkownik powiązany ze slotem Team. Preferuj TournamentRegistration.team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='entry_mode',
            field=models.CharField(choices=[('MANAGER', 'Organizator + asystenci'), ('ORGANIZER_ONLY', 'Tylko organizator')], default='MANAGER', max_length=32),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_code',
            field=models.CharField(blank=True, help_text='Kod dołączania uczestników (JOIN) używany, gdy join_enabled=true.', max_length=32, null=True),
        ),
    ]
