# Generated by Django 5.0.8 on 2026-01-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_tournament_join_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants_public_preview_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Czy zarejestrowani uczestnicy mogą oglądać TournamentPublic przed publikacją turnieju.'),
        ),
    ]
