# Generated by Django 5.0.8 on 2026-01-17 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_tournament_participants_public_preview_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants_self_rename_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='Czy uczestnicy mogą samodzielnie zmieniać nazwę (bez akceptacji organizatora/asystenta).'),
        ),
        migrations.CreateModel(
            name='TeamNameChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(max_length=255)),
                ('requested_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('APPROVED', 'Zaakceptowana'), ('REJECTED', 'Odrzucona')], db_index=True, default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_name_change_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_name_change_requests', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_change_requests', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_change_requests', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='teamnamechangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('team',), name='uniq_pending_name_change_per_team'),
        ),
    ]
