# Generated by Django 5.0.8 on 2026-01-18 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0028_tournament_participants_self_rename_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='clock_added_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Dodatkowy czas doliczony do bieżącego okresu (np. doliczony czas w piłce nożnej).'),
        ),
        migrations.AddField(
            model_name='match',
            name='clock_elapsed_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Skumulowany czas (w sekundach) w obrębie bieżącego okresu, bez aktualnie trwającego odcinka.'),
        ),
        migrations.AddField(
            model_name='match',
            name='clock_period',
            field=models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)')], db_index=True, default='NONE', help_text='Bieżący okres gry (np. połowa, dogrywka), istotny dla wyliczeń minut incydentów.', max_length=8),
        ),
        migrations.AddField(
            model_name='match',
            name='clock_started_at',
            field=models.DateTimeField(blank=True, help_text='Znacznik czasu uruchomienia aktualnego odcinka pomiaru czasu.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='clock_state',
            field=models.CharField(choices=[('NOT_STARTED', 'Nie rozpoczęty'), ('RUNNING', 'W trakcie'), ('PAUSED', 'Wstrzymany'), ('STOPPED', 'Zatrzymany')], db_index=True, default='NOT_STARTED', help_text='Stan zegara wykorzystywanego do rejestrowania czasu zdarzeń meczowych.', max_length=16),
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('jersey_number', models.PositiveIntegerField(blank=True, help_text='Indywidualny numer zawodnika (np. numer koszulki).', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flaga logicznej aktywności zawodnika, pozwalająca zachować historię zdarzeń.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Użytkownik, który wprowadził zawodnika do składu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_players', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.team')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MatchIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('GOAL', 'Bramka'), ('YELLOW_CARD', 'Żółta kartka'), ('RED_CARD', 'Czerwona kartka'), ('FOUL', 'Faul'), ('SUBSTITUTION', 'Zmiana'), ('HANDBALL_TWO_MINUTES', 'Kara 2 min (ręczna)'), ('TENNIS_CODE_VIOLATION', 'Naruszenie przepisów (tenis)'), ('TIMEOUT', 'Przerwa/timeout')], db_index=True, max_length=40)),
                ('period', models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)')], db_index=True, default='NONE', help_text='Okres gry w momencie rejestracji zdarzenia (np. połowa, dogrywka).', max_length=8)),
                ('time_source', models.CharField(choices=[('CLOCK', 'Zegar meczu'), ('MANUAL', 'Wprowadzony ręcznie')], default='CLOCK', help_text='Źródło czasu zdarzenia, istotne przy korektach oraz analizie przebiegu meczu.', max_length=8)),
                ('minute', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Minuta zdarzenia liczona w osi czasu meczu (może być pusta w dyscyplinach bez zegara).', null=True)),
                ('minute_raw', models.CharField(blank=True, help_text="Oryginalny zapis minuty (np. '90+3'), umożliwiający wierną prezentację w interfejsie.", max_length=12, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Dodatkowe dane zależne od dyscypliny i typu zdarzenia (np. szczegóły kary, opis).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Użytkownik rejestrujący zdarzenie w systemie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_incidents', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='tournaments.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='tournaments.team')),
                ('player', models.ForeignKey(blank=True, help_text='Zawodnik powiązany ze zdarzeniem jednoosobowym (np. kartka, faul).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='tournaments.teamplayer')),
                ('player_in', models.ForeignKey(blank=True, help_text='Zawodnik wchodzący na boisko (dla zdarzenia typu zmiana).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_in', to='tournaments.teamplayer')),
                ('player_out', models.ForeignKey(blank=True, help_text='Zawodnik schodzący z boiska (dla zdarzenia typu zmiana).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_out', to='tournaments.teamplayer')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='teamplayer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('jersey_number__isnull', False)), fields=('team', 'jersey_number'), name='uniq_active_jersey_number_per_team'),
        ),
        migrations.AddIndex(
            model_name='matchincident',
            index=models.Index(fields=['match', 'created_at'], name='idx_incident_match_time'),
        ),
        migrations.AddIndex(
            model_name='matchincident',
            index=models.Index(fields=['match', 'team', 'kind'], name='idx_incident_match_team_kind'),
        ),
        migrations.AddConstraint(
            model_name='matchincident',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'SUBSTITUTION'), _negated=True), models.Q(('player_in__isnull', False), ('player_out__isnull', False)), _connector='OR'), name='substitution_requires_players_in_out'),
        ),
        migrations.AddConstraint(
            model_name='matchincident',
            constraint=models.CheckConstraint(check=models.Q(('kind', 'SUBSTITUTION'), models.Q(('player_in__isnull', True), ('player_out__isnull', True)), _connector='OR'), name='non_substitution_has_no_players_in_out'),
        ),
    ]
