# Generated by Django 5.0.8 on 2026-01-18 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0029_match_clock_added_seconds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchincident',
            name='substitution_requires_players_in_out',
        ),
        migrations.RemoveConstraint(
            model_name='matchincident',
            name='non_substitution_has_no_players_in_out',
        ),
        migrations.RenameIndex(
            model_name='matchincident',
            new_name='idx_incident_m_team_kind',
            old_name='idx_incident_match_team_kind',
        ),
        migrations.AddConstraint(
            model_name='matchincident',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'SUBSTITUTION'), _negated=True), models.Q(('player_in__isnull', False), ('player_out__isnull', False)), _connector='OR'), name='sub_req_players_in_out'),
        ),
        migrations.AddConstraint(
            model_name='matchincident',
            constraint=models.CheckConstraint(check=models.Q(('kind', 'SUBSTITUTION'), models.Q(('player_in__isnull', True), ('player_out__isnull', True)), _connector='OR'), name='non_sub_no_players_in_out'),
        ),
    ]
