# Generated by Django 5.0.8 on 2026-01-18 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0030_remove_matchincident_substitution_requires_players_in_out_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tennis_state',
            field=models.JSONField(blank=True, default=None, help_text='Dla tenisa: bieżący stan punktów/gemów. Przykład: {home_games, away_games, home_points, away_points, in_tiebreak, home_tb, away_tb, set_index}.', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='clock_period',
            field=models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)')], db_index=True, default='NONE', help_text='Bieżący okres gry (np. połowa, dogrywka).', max_length=8),
        ),
        migrations.AlterField(
            model_name='match',
            name='tennis_sets',
            field=models.JSONField(blank=True, default=None, help_text='Dla tenisa: lista zakończonych setów w gemach (opcjonalnie z tie-breakiem).', null=True),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='kind',
            field=models.CharField(choices=[('GOAL', 'Bramka'), ('PENALTY_SCORED', 'Rzut karny (gol)'), ('PENALTY_MISSED', 'Rzut karny (niewykorzystany)'), ('YELLOW_CARD', 'Żółta kartka'), ('RED_CARD', 'Czerwona kartka'), ('FOUL', 'Faul'), ('SUBSTITUTION', 'Zmiana'), ('HANDBALL_TWO_MINUTES', 'Kara 2 min (ręczna)'), ('TENNIS_POINT', 'Punkt (tenis)'), ('TENNIS_CODE_VIOLATION', 'Naruszenie przepisów (tenis)'), ('TIMEOUT', 'Przerwa/timeout')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Dodatkowe dane zależne od dyscypliny i typu zdarzenia.'),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='minute',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Minuta zdarzenia w osi czasu meczu (może być pusta w dyscyplinach bez zegara).', null=True),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='minute_raw',
            field=models.CharField(blank=True, help_text="Oryginalny zapis minuty (np. '90+3'), do wiernej prezentacji.", max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Zawodnik zdarzenia jednoosobowego (kartka, faul).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='tournaments.teamplayer'),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='player_in',
            field=models.ForeignKey(blank=True, help_text='Zawodnik wchodzący (zmiana).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_in', to='tournaments.teamplayer'),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='player_out',
            field=models.ForeignKey(blank=True, help_text='Zawodnik schodzący (zmiana).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_out', to='tournaments.teamplayer'),
        ),
    ]
