# Generated by Django 5.0.8 on 2026-02-19 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0031_match_tennis_state_alter_match_clock_period_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCommentaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)')], db_index=True, default='NONE', help_text='Okres gry w momencie dodania komentarza (np. połowa, dogrywka).', max_length=8)),
                ('time_source', models.CharField(choices=[('CLOCK', 'Zegar meczu'), ('MANUAL', 'Wprowadzony ręcznie')], default='CLOCK', help_text='Źródło czasu komentarza, istotne przy korektach oraz analizie osi czasu.', max_length=8)),
                ('minute', models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Minuta komentarza w osi czasu meczu (może być pusta w dyscyplinach bez zegara).', null=True)),
                ('minute_raw', models.CharField(blank=True, help_text="Oryginalny zapis minuty (np. '90+3'), do wiernej prezentacji.", max_length=12, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_commentary_entries', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentary_entries', to='tournaments.match')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['match', 'created_at'], name='idx_comm_match_time'), models.Index(fields=['match', 'minute'], name='idx_comm_match_minute')],
            },
        ),
        migrations.CreateModel(
            name='TournamentCommentaryPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TOKEN', 'Słowo'), ('TEMPLATE', 'Zwrot')], db_index=True, default='TOKEN', max_length=16)),
                ('category', models.CharField(blank=True, db_index=True, help_text='Opcjonalna kategoria UI (np. akcje, oceny, gotowce).', max_length=40, null=True)),
                ('text', models.CharField(max_length=280)),
                ('order', models.PositiveIntegerField(default=0, help_text='Kolejność prezentacji w UI w ramach (kind, category).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flaga logicznej aktywności, pozwalająca zachować historię zmian słownika.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commentary_phrases', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentary_phrases', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['kind', 'category', 'order', 'id'],
                'indexes': [models.Index(fields=['tournament', 'kind', 'is_active'], name='idx_phrase_t_kind_on')],
            },
        ),
    ]
