# Generated by Django 5.0.8 on 2026-03-26 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0032_matchcommentaryentry_tournamentcommentaryphrase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='custom_discipline_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='result_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='result_mode',
            field=models.CharField(choices=[('SCORE', 'Klasyczny wynik'), ('CUSTOM', 'Wynik niestandardowy')], default='SCORE', max_length=16),
        ),
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Grupa (tylko dla fazy grupowej).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.group'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Numer kolejki / rundy.', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Zwycięzca meczu (wymagany w KO).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='registered_user',
            field=models.ForeignKey(blank=True, help_text='(Opcjonalne) Użytkownik powiązany ze slotem Team. Preferuj TournamentRegistration.team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='discipline',
            field=models.CharField(choices=[('football', 'Piłka nożna'), ('volleyball', 'Siatkówka'), ('basketball', 'Koszykówka'), ('handball', 'Piłka ręczna'), ('tennis', 'Tenis'), ('wrestling', 'Zapasy'), ('custom', 'Inna / niestandardowa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Logiczne archiwum - turniej ukryty na głównych listach.'),
        ),
        migrations.CreateModel(
            name='MatchCustomResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_kind', models.CharField(choices=[('NUMBER', 'Liczba'), ('TIME', 'Czas')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, help_text='Wartość liczbowa dla trybu NUMBER.', max_digits=14, null=True)),
                ('time_ms', models.BigIntegerField(blank=True, help_text='Wartość czasu w milisekundach dla trybu TIME.', null=True)),
                ('display_value', models.CharField(blank=True, default='', help_text='Sformatowana wartość prezentacyjna zwracana do UI.', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_match_custom_results', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_results', to='tournaments.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_match_results', to='tournaments.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_match_custom_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', 'id'],
                'indexes': [models.Index(fields=['match', 'rank'], name='idx_custom_result_match_rank'), models.Index(fields=['team', 'match'], name='idx_custom_result_team_match')],
            },
        ),
        migrations.AddConstraint(
            model_name='matchcustomresult',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='uniq_custom_result_match_team'),
        ),
        migrations.AddConstraint(
            model_name='matchcustomresult',
            constraint=models.CheckConstraint(check=models.Q(('numeric_value__isnull', False), ('time_ms__isnull', False), _connector='OR'), name='custom_result_has_some_value'),
        ),
        migrations.AddConstraint(
            model_name='matchcustomresult',
            constraint=models.CheckConstraint(check=models.Q(('time_ms__isnull', True), ('time_ms__gte', 0), _connector='OR'), name='custom_result_time_ms_non_negative'),
        ),
    ]
