# Generated by Django 5.0.8 on 2026-03-27 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0033_tournament_custom_discipline_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageMassStartResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(default=1, help_text='Numer próby / rundy w obrębie etapu.')),
                ('value_kind', models.CharField(choices=[('NUMBER', 'Liczba'), ('TIME', 'Czas'), ('PLACE', 'Miejsce')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('time_ms', models.BigIntegerField(blank=True, null=True)),
                ('place_value', models.PositiveIntegerField(blank=True, null=True)),
                ('display_value', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group_id', 'rank', 'round_number', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='matchcustomresult',
            name='custom_result_has_some_value',
        ),
        migrations.AddField(
            model_name='matchcustomresult',
            name='place_value',
            field=models.PositiveIntegerField(blank=True, help_text='Miejsce dla trybu PLACE.', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='competition_model',
            field=models.CharField(choices=[('HEAD_TO_HEAD', 'Pojedynki / mecze'), ('MASS_START', 'Wszyscy razem')], default='HEAD_TO_HEAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchcustomresult',
            name='value_kind',
            field=models.CharField(choices=[('NUMBER', 'Liczba'), ('TIME', 'Czas'), ('PLACE', 'Miejsce')], max_length=16),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('LEAGUE', 'Liga'), ('GROUP', 'Faza grupowa'), ('KNOCKOUT', 'Puchar (KO)'), ('THIRD_PLACE', 'Mecz o 3. miejsce'), ('MASS_START', 'Etap wszyscy razem')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='matchcustomresult',
            constraint=models.CheckConstraint(check=models.Q(('numeric_value__isnull', False), ('time_ms__isnull', False), ('place_value__isnull', False), _connector='OR'), name='custom_result_has_some_value'),
        ),
        migrations.AddConstraint(
            model_name='matchcustomresult',
            constraint=models.CheckConstraint(check=models.Q(('place_value__isnull', True), ('place_value__gte', 1), _connector='OR'), name='custom_result_place_positive'),
        ),
        migrations.AddField(
            model_name='stagemassstartresult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mass_start_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagemassstartresult',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_start_results', to='tournaments.group'),
        ),
        migrations.AddField(
            model_name='stagemassstartresult',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_start_results', to='tournaments.stage'),
        ),
        migrations.AddField(
            model_name='stagemassstartresult',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_start_stage_results', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='stagemassstartresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mass_start_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stagemassstartresult',
            index=models.Index(fields=['stage', 'group', 'rank'], name='idx_mass_stage_group_rank'),
        ),
        migrations.AddIndex(
            model_name='stagemassstartresult',
            index=models.Index(fields=['team', 'stage'], name='idx_mass_team_stage'),
        ),
        migrations.AddConstraint(
            model_name='stagemassstartresult',
            constraint=models.UniqueConstraint(fields=('stage', 'team', 'round_number'), name='uniq_mass_start_stage_team_round'),
        ),
        migrations.AddConstraint(
            model_name='stagemassstartresult',
            constraint=models.CheckConstraint(check=models.Q(('numeric_value__isnull', False), ('time_ms__isnull', False), ('place_value__isnull', False), _connector='OR'), name='mass_start_result_has_some_value'),
        ),
        migrations.AddConstraint(
            model_name='stagemassstartresult',
            constraint=models.CheckConstraint(check=models.Q(('time_ms__isnull', True), ('time_ms__gte', 0), _connector='OR'), name='mass_start_result_time_ms_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stagemassstartresult',
            constraint=models.CheckConstraint(check=models.Q(('place_value__isnull', True), ('place_value__gte', 1), _connector='OR'), name='mass_start_result_place_positive'),
        ),
    ]
