# Generated by Django 5.0.8 on 2026-03-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0034_stagemassstartresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, help_text='Lokalizacja przypisana do konkretnej grupy etapu.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Data obowiązująca dla grupy w harmonogramie trybu MASS_START.', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Godzina obowiązująca dla grupy w harmonogramie trybu MASS_START.', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='location',
            field=models.CharField(blank=True, help_text='Domyślna lokalizacja całego etapu w harmonogramie trybu MASS_START.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Data obowiązująca dla całego etapu, gdy harmonogram jest planowany etapami.', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Godzina obowiązująca dla całego etapu, gdy harmonogram jest planowany etapami.', null=True),
        ),
    ]
