# Generated by Django 5.0.8 on 2026-04-02 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0035_group_location_group_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Zaplanowany'), ('OPEN', 'Otwarty'), ('CLOSED', 'Zamknięty')], default='OPEN', max_length=10),
        ),
        migrations.CreateModel(
            name='StageMassStartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField(blank=True, help_text='Kolejność wejściowa uczestnika w obrębie wygenerowanego etapu.', null=True)),
                ('source_rank', models.PositiveIntegerField(blank=True, help_text='Miejsce zajęte w etapie źródłowym podczas generowania awansu.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flaga logicznej aktywności wpisu obsady etapu.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mass_start_entries', to='tournaments.group')),
                ('source_group', models.ForeignKey(blank=True, help_text='Grupa źródłowa, z której uczestnik awansował do bieżącego etapu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_mass_start_entries', to='tournaments.group')),
                ('source_stage', models.ForeignKey(blank=True, help_text='Etap źródłowy, z którego uczestnik awansował do bieżącego etapu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advanced_mass_start_entries', to='tournaments.stage')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_start_entries', to='tournaments.stage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_start_entries', to='tournaments.team')),
            ],
            options={
                'ordering': ['stage_id', 'group_id', 'seed', 'team_id', 'id'],
                'indexes': [models.Index(fields=['stage', 'group', 'seed'], name='idx_mse_stage_grp_seed'), models.Index(fields=['team', 'stage'], name='idx_mass_entry_team_stage')],
            },
        ),
        migrations.AddConstraint(
            model_name='stagemassstartentry',
            constraint=models.UniqueConstraint(fields=('stage', 'team'), name='uniq_mass_start_entry_stage_team'),
        ),
    ]
