# Generated by Django 5.0.8 on 2026-04-04 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0036_alter_stage_status_stagemassstartentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='tournamentregistration',
            name='uniq_registration_tournament_user',
        ),
        migrations.AddField(
            model_name='division',
            name='competition_model',
            field=models.CharField(choices=[('HEAD_TO_HEAD', 'Pojedynki / mecze'), ('MASS_START', 'Wszyscy razem')], default='HEAD_TO_HEAD', max_length=20),
        ),
        migrations.AddField(
            model_name='division',
            name='competition_type',
            field=models.CharField(choices=[('TEAM', 'Drużynowy'), ('INDIVIDUAL', 'Indywidualny')], default='TEAM', max_length=16),
        ),
        migrations.AddField(
            model_name='division',
            name='format_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='division',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Logiczne archiwum dywizji bez usuwania jej historii sportowej.'),
        ),
        migrations.AddField(
            model_name='division',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Flaga wskazuje dywizję domyślnie otwieraną w panelu oraz w widokach publicznych.'),
        ),
        migrations.AddField(
            model_name='division',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Kolejność prezentacji dywizji w obrębie turnieju.'),
        ),
        migrations.AddField(
            model_name='division',
            name='result_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='division',
            name='result_mode',
            field=models.CharField(choices=[('SCORE', 'Klasyczny wynik'), ('CUSTOM', 'Wynik niestandardowy')], default='SCORE', max_length=16),
        ),
        migrations.AddField(
            model_name='division',
            name='slug',
            field=models.SlugField(blank=True, help_text='Stabilny identyfikator dywizji wykorzystywany w URL i przełączaniu kontekstu.', max_length=140),
        ),
        migrations.AddField(
            model_name='division',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Szkic'), ('CONFIGURED', 'Skonfigurowany'), ('RUNNING', 'W trakcie'), ('FINISHED', 'Zakończony')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='division',
            name='tournament_format',
            field=models.CharField(choices=[('CUP', 'Puchar'), ('LEAGUE', 'Liga'), ('MIXED', 'Mieszany')], default='LEAGUE', max_length=16),
        ),
        migrations.AddField(
            model_name='division',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Dywizja rejestracji. Pole pozostaje opcjonalne wyłącznie na czas migracji starszych danych.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='tournaments.division'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Dywizja etapu. Pole pozostaje opcjonalne wyłącznie na czas migracji starszych danych.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='tournaments.division'),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Dywizja uczestnika. Pole pozostaje opcjonalne wyłącznie na czas migracji starszych danych.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='tournaments.division'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['tournament', 'order'], name='idx_division_tournament_order'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['tournament', 'is_archived'], name='idx_division_tournament_arch'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('tournament', 'slug'), name='uniq_tournament_division_slug'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tournament',), name='uniq_default_division_per_tournament'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(condition=models.Q(('division__isnull', False)), fields=('division', 'order'), name='uniq_stage_order_per_division'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(condition=models.Q(('division__isnull', True)), fields=('tournament', 'order'), name='uniq_stage_order_per_tournament_without_division'),
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('division__isnull', False)), fields=('division', 'user'), name='uniq_registration_division_user'),
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('division__isnull', True)), fields=('tournament', 'user'), name='uniq_registration_tournament_user_without_division'),
        ),
    ]
