# Generated by Django 5.0.8 on 2026-04-07 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0037_alter_division_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='Użytkownik, który utworzył lub ponowił zaproszenie asystenta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tournament_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmembership',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='Znacznik czasu akceptacji albo odrzucenia zaproszenia asystenta.', null=True),
        ),
        migrations.AddField(
            model_name='tournamentmembership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Oczekuje'), ('ACCEPTED', 'Zaakceptowane'), ('DECLINED', 'Odrzucone')], db_index=True, default='PENDING', help_text='Status zaproszenia asystenta w obrębie turnieju.', max_length=16),
        ),
    ]
