# Generated by Django 5.0.8 on 2026-04-07 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0038_tournamentmembership_invited_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAssistantInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(help_text='Adres e-mail, na który zostało zapisane zaproszenie asystenta.', max_length=254)),
                ('normalized_email', models.CharField(db_index=True, help_text='Znormalizowany adres e-mail używany do dopasowania zaproszenia po logowaniu.', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('ACCEPTED', 'Zaakceptowane'), ('DECLINED', 'Odrzucone'), ('CANCELED', 'Cofnięte')], db_index=True, default='PENDING', help_text='Status zaproszenia asystenta zapisany niezależnie od istnienia konta użytkownika.', max_length=16)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Uprawnienia, które zostaną nadane po akceptacji zaproszenia.')),
                ('responded_at', models.DateTimeField(blank=True, help_text='Znacznik czasu akceptacji, odrzucenia albo cofnięcia zaproszenia.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, help_text='Organizator, który utworzył albo ponowił zaproszenie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tournament_assistant_invites', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_invites', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentassistantinvite',
            constraint=models.UniqueConstraint(fields=('tournament', 'normalized_email'), name='uniq_tournament_assistant_invite_email'),
        ),
    ]
