# Generated by Django 5.0.8 on 2026-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0042_remove_match_away_classification_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_classification_points',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Punkty klasyfikacyjne strony niebieskiej / away w zapasach.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_classification_points',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Punkty klasyfikacyjne strony czerwonej / home w zapasach.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='wrestling_result_method',
            field=models.CharField(blank=True, default='', help_text='Kod sposobu zwycięstwa w zapasach, np. VFA, VSU, VPO, VIN, VFO, DSQ.', max_length=24),
        ),
        migrations.AlterField(
            model_name='match',
            name='clock_period',
            field=models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)')], db_index=True, default='NONE', help_text='Bieżący okres gry (np. połowa, dogrywka).', max_length=8),
        ),
        migrations.AlterField(
            model_name='matchcommentaryentry',
            name='period',
            field=models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)')], db_index=True, default='NONE', help_text='Okres gry w momencie dodania komentarza (np. połowa, dogrywka).', max_length=8),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='kind',
            field=models.CharField(choices=[('GOAL', 'Bramka'), ('PENALTY_SCORED', 'Rzut karny (gol)'), ('PENALTY_MISSED', 'Rzut karny (niewykorzystany)'), ('YELLOW_CARD', 'Żółta kartka'), ('RED_CARD', 'Czerwona kartka'), ('FOUL', 'Faul'), ('SUBSTITUTION', 'Zmiana'), ('HANDBALL_TWO_MINUTES', 'Kara 2 min (ręczna)'), ('TENNIS_POINT', 'Punkt (tenis)'), ('TENNIS_CODE_VIOLATION', 'Naruszenie przepisów (tenis)'), ('TIMEOUT', 'Przerwa/timeout'), ('WRESTLING_POINT_1', 'Punkt techniczny 1 (zapasy)'), ('WRESTLING_POINT_2', 'Punkty techniczne 2 (zapasy)'), ('WRESTLING_POINT_4', 'Punkty techniczne 4 (zapasy)'), ('WRESTLING_POINT_5', 'Punkty techniczne 5 (zapasy)'), ('WRESTLING_PASSIVITY', 'Pasywność (zapasy)'), ('WRESTLING_CAUTION', 'Ostrzeżenie (zapasy)'), ('WRESTLING_FALL', 'Tusz (zapasy)'), ('WRESTLING_INJURY', 'Kontuzja (zapasy)'), ('WRESTLING_FORFEIT', 'Walkower (zapasy)'), ('WRESTLING_DISQUALIFICATION', 'Dyskwalifikacja (zapasy)')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='period',
            field=models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)')], db_index=True, default='NONE', help_text='Okres gry w momencie rejestracji zdarzenia (np. połowa, dogrywka).', max_length=8),
        ),
    ]
