# Generated by Django 5.0.8 on 2026-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0043_match_away_classification_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='clock_period',
            field=models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)'), ('P1', '1 okres (zapasy)'), ('BREAK', 'Przerwa (zapasy)'), ('P2', '2 okres (zapasy)'), ('Q1', '1 kwarta'), ('Q2', '2 kwarta'), ('Q3', '3 kwarta'), ('Q4', '4 kwarta'), ('OT1', 'Dogrywka 1 (koszykówka)'), ('OT2', 'Dogrywka 2 (koszykówka)'), ('OT3', 'Dogrywka 3 (koszykówka)'), ('OT4', 'Dogrywka 4 (koszykówka)')], db_index=True, default='NONE', help_text='Bieżący okres gry (np. połowa, dogrywka).', max_length=8),
        ),
        migrations.AlterField(
            model_name='matchcommentaryentry',
            name='period',
            field=models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)'), ('P1', '1 okres (zapasy)'), ('BREAK', 'Przerwa (zapasy)'), ('P2', '2 okres (zapasy)'), ('Q1', '1 kwarta'), ('Q2', '2 kwarta'), ('Q3', '3 kwarta'), ('Q4', '4 kwarta'), ('OT1', 'Dogrywka 1 (koszykówka)'), ('OT2', 'Dogrywka 2 (koszykówka)'), ('OT3', 'Dogrywka 3 (koszykówka)'), ('OT4', 'Dogrywka 4 (koszykówka)')], db_index=True, default='NONE', help_text='Okres gry w momencie dodania komentarza (np. połowa, dogrywka).', max_length=8),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='period',
            field=models.CharField(choices=[('NONE', 'Brak'), ('FH', '1 połowa'), ('SH', '2 połowa'), ('ET1', 'Dogrywka 1'), ('ET2', 'Dogrywka 2'), ('H1', '1 połowa (ręczna)'), ('H2', '2 połowa (ręczna)'), ('P1', '1 okres (zapasy)'), ('BREAK', 'Przerwa (zapasy)'), ('P2', '2 okres (zapasy)'), ('Q1', '1 kwarta'), ('Q2', '2 kwarta'), ('Q3', '3 kwarta'), ('Q4', '4 kwarta'), ('OT1', 'Dogrywka 1 (koszykówka)'), ('OT2', 'Dogrywka 2 (koszykówka)'), ('OT3', 'Dogrywka 3 (koszykówka)'), ('OT4', 'Dogrywka 4 (koszykówka)')], db_index=True, default='NONE', help_text='Okres gry w momencie rejestracji zdarzenia (np. połowa, dogrywka).', max_length=8),
        ),
    ]
