# Generated by Django 5.0.8 on 2026-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0044_alter_match_clock_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='tournament_format',
            field=models.CharField(choices=[('CUP', 'Faza pucharowa'), ('LEAGUE', 'Liga'), ('MIXED', 'Grupy + puchar')], default='LEAGUE', max_length=16),
        ),
        migrations.AlterField(
            model_name='matchincident',
            name='kind',
            field=models.CharField(choices=[('GOAL', 'Bramka'), ('PENALTY_SCORED', 'Rzut karny (gol)'), ('PENALTY_MISSED', 'Rzut karny (niewykorzystany)'), ('YELLOW_CARD', 'Żółta kartka'), ('RED_CARD', 'Czerwona kartka'), ('FOUL', 'Faul'), ('SUBSTITUTION', 'Zmiana'), ('HANDBALL_TWO_MINUTES', 'Kara 2 min (ręczna)'), ('TENNIS_POINT', 'Punkt (tenis)'), ('TENNIS_CODE_VIOLATION', 'Naruszenie przepisów (tenis)'), ('TIMEOUT', 'Przerwa na żądanie'), ('WRESTLING_POINT_1', 'Punkt techniczny 1 (zapasy)'), ('WRESTLING_POINT_2', 'Punkty techniczne 2 (zapasy)'), ('WRESTLING_POINT_4', 'Punkty techniczne 4 (zapasy)'), ('WRESTLING_POINT_5', 'Punkty techniczne 5 (zapasy)'), ('WRESTLING_PASSIVITY', 'Pasywność (zapasy)'), ('WRESTLING_CAUTION', 'Ostrzeżenie (zapasy)'), ('WRESTLING_FALL', 'Tusz (zapasy)'), ('WRESTLING_INJURY', 'Kontuzja (zapasy)'), ('WRESTLING_FORFEIT', 'Walkower (zapasy)'), ('WRESTLING_DISQUALIFICATION', 'Dyskwalifikacja (zapasy)')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('LEAGUE', 'Liga'), ('GROUP', 'Faza grupowa'), ('KNOCKOUT', 'Faza pucharowa'), ('THIRD_PLACE', 'Mecz o 3. miejsce'), ('MASS_START', 'Etap wszyscy razem')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='join_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Czy użytkownicy mogą dołączać do turnieju przez konto i kod dołączania.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participants_public_preview_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Czy zarejestrowani uczestnicy mogą oglądać widok publiczny przed publikacją turnieju.'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_code',
            field=models.CharField(blank=True, help_text='Kod dołączania uczestników używany, gdy dołączanie przez konto jest włączone.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_format',
            field=models.CharField(choices=[('CUP', 'Faza pucharowa'), ('LEAGUE', 'Liga'), ('MIXED', 'Grupy + puchar')], default='LEAGUE', max_length=16),
        ),
    ]
