# Generated by Django 5.0.8 on 2026-04-27 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0045_alter_division_tournament_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('APPROVED', 'Zaakceptowana'), ('REJECTED', 'Odrzucona')], db_index=True, default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_division_change_decisions', to=settings.AUTH_USER_MODEL)),
                ('from_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_division_change_requests', to='tournaments.division')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_change_requests', to='tournaments.tournamentregistration')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_division_change_requests', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_change_requests', to='tournaments.team')),
                ('to_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_division_change_requests', to='tournaments.division')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_change_requests', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='divisionchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('registration',), name='uniq_pending_division_change_per_registration'),
        ),
    ]
