# Generated by Django 5.0.8 on 2026-04-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0047_remove_stagemassstartresult_mass_start_result_has_some_value_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stage',
            name='uniq_stage_order_per_division',
        ),
        migrations.RemoveConstraint(
            model_name='stage',
            name='uniq_stage_order_per_tournament_without_division',
        ),
        migrations.AddField(
            model_name='stage',
            name='archive_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='stage',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(condition=models.Q(('division__isnull', False), ('is_archived', False)), fields=('division', 'order'), name='uniq_active_stage_order_per_division'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(condition=models.Q(('division__isnull', True), ('is_archived', False)), fields=('tournament', 'order'), name='uniq_active_stage_order_per_tournament_without_division'),
        ),
    ]
