# Generated by Django 5.0.8 on 2026-05-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0048_remove_stage_uniq_stage_order_per_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='discipline',
            field=models.CharField(choices=[('football', 'Piłka nożna'), ('basketball', 'Koszykówka'), ('handball', 'Piłka ręczna'), ('tennis', 'Tenis'), ('wrestling', 'Zapasy'), ('custom', 'Inna / niestandardowa')], max_length=50),
        ),
    ]
